### ISSUE TITLE
issues compiling with go from source 

### ISSUE THREAD

**Issue by pricesgoingup** [octu0/dstat-graph#1]
bk@sneak:~/Downloads/dstat-graph-1.0.0$ make pkg
go get gopkg.in/urfave/cli.v1
go get github.com/comail/colog
go get github.com/wcharczuk/go-chart
go generate
mkdir -p pkg
GOOS=linux GOARCH=amd64 go build -o pkg/dstat-graph_linux_amd64-1.0.0 cmd/main.go
# github.com/octu0/dstat-graph
/usr/local/go/src/github.com/octu0/dstat-graph/linechart.go:75:9: unknown field 'Show' in struct literal of type chart.Style
/usr/local/go/src/github.com/octu0/dstat-graph/linechart.go:92:14: undefined: chart.StyleShow
/usr/local/go/src/github.com/octu0/dstat-graph/linechart.go:98:23: undefined: chart.StyleShow
/usr/local/go/src/github.com/octu0/dstat-graph/linechart.go:110:9: unknown field 'Show' in struct literal of type chart.Style
make: *** [Makefile:36: pkg-linux-amd64] Error 2

**Comment by octu0** [comment]
thank you for your report
i was fix it. 
https://github.com/octu0/dstat-graph/releases/tag/v1.0.1
