### ISSUE TITLE
Error while trying to launch dstat-graph: csv read error: EOF

### ISSUE THREAD

**Issue by ArtObr** [octu0/dstat-graph#3]
Hi there, I've run simple dstat output.
` dstat -t --cpu --mem --disk --io --net --int --sys --tcp --output ./dstat.csv`
Then, I've compiled dstat-graph sources and tryed to run dstat-graph on this output.
`./dstat-graph_linux_amd64-1.0.1 --csv ./dstat.csv -o cpu.png -f usr,sys,idl,wai`
But i get an error:
```
[ error ] 2020/10/29 17:10:10 main.go:78: csv read error: EOF
[ error ] 2020/10/29 17:10:10 main.go:147: EOF
```
Do you know what issue that could be? I didn't edited dstat file in any ways.

**Comment by octu0** [comment]
Perhaps the CSV version output by dstat is a bit old.
For example, the output would look like this
```csv
"Dstat 0.7.0 CSV output"
"Author:","Dag Wieers <dag@wieers.com>",,,,"URL:","http://dag.wieers.com/home-made/dstat/"
"Host:","dev-dist-app",,,,"User:","yusuke.hata"
"Cmdline:","dstat -t --cpu --mem --disk --io --net --int --sys --tcp --output ./dstat.csv",,,,"Date:","02 Nov 2020 12:07:30 JST"

"system","total cpu usage",,,,,,"memory usage",,,,"dsk/total",,"io/total",,"net/total",,"interrupts",,,"system",,"tcp sockets",,,,
"date/time","usr","sys","idl","wai","hiq","siq","used","buff","cach","free","read","writ","read","writ","recv","send","42","43","44","int","csw","lis","act","syn","tim","clo"
02-11 12:07:30,9.316,5.457,83.522,1.452,0.000,0.252,8261812224.0,1433620480.0,8042459136.0,13950648320.0,3233.893,4747317.272,0.107,396.416,0.0,0.0,0.000,17.868,0.000,1122.346,20501.955,41.0,299.0,2.0,771.0,1.0
:
:
```

Try upgrading your dstat (at least dstat version 0.7.3 should work)
The output should be as follows
```
"Dstat 0.7.3 CSV output"
"Author:","Dag Wieers <dag@wieers.com>",,,,"URL:","http://dag.wieers.com/home-made/dstat/"
"Host:","4219d883cfac",,,,"User:","yusuke.hata"
"Cmdline:","dstat -t --cpu --mem --disk --io --net --int --sys --tcp --output ./dstat.csv",,,,"Date:","02 Nov 2020 03:11:01 UTC"
"system","total cpu usage",,,,,"memory usage",,,,"dsk/total",,"io/total",,"net/total",,"interrupts",,,"system",,"tcp sockets",,,,
"time","usr","sys","idl","wai","stl","used","free","buff","cach","read","writ","read","writ","recv","send","27","28","32","int","csw","lis","act","syn","tim","clo"
02-11 03:11:01,5.839,3.487,89.990,0.684,0,848187392,193552384,1074905088,1197166592,40347.855,226242.507,3.299,13.922,0,0,17.803,16.036,14.348,745.388,2542.974,0,0,0,3,0
:
:
```

**Comment by ArtObr** [comment]
I had dstat version 0.7.2, then compiled from source 0.7.3 from here:
https://github.com/dstat-real/dstat/tree/master
But still the same mistake.
Maybe I need to use 0.7.3 from some rh repo?

**Comment by host452b** [comment]
same error

**Comment by host452b** [comment]
[ error ] 2020/11/28 11:55:44 main.go:78: csv read error: EOF
[ error ] 2020/11/28 11:55:44 main.go:147: EOF

**Comment by octu0** [comment]
I got an older version of dstat, so I don't think I'm getting EOF anymore, even if I'm using pre-0.7.3 csv
I hope you'll try the 1.0.2 version
https://github.com/octu0/dstat-graph/releases/tag/v1.0.2
